name: Deploy TNDS services to GitHub Pages

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Maximise build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
        
      - name: Checkout gh-pages branch of uk-bus-open-data
        uses: actions/checkout@v6
        with:
          repository: xavier114fch/uk-bus-open-data
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ref: gh-pages
          path: uk-bus-open-data
      
      - name: Copy TNDS services data only
        run: |
          mkdir -p services
          rm -rf bods/
          rm -rf naptan/
          rm -rf noc/
          rm -rf nptg/
          rm -rf tnds/stopPoints/
          rm -f tnds/all_stop_points.json
          rm -f tnds/stops_tnds_only.json
          cp -r uk-bus-open-data/data/tnds/ services/

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: services

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
