name: Deploy TNDS services to GitHub Pages

on:
  workflow_dispatch:
  # schedule:
  #  - cron: '0 * * * *'

permissions:
  contents: read
  pages: write
  id-token: write
  actions: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Maximise build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
      
      - name: Checkout gh-pages branch of uk-bus-open-data
        uses: actions/checkout@v6
        with:
          repository: xavier114fch/uk-bus-open-data
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ref: gh-pages
          path: uk-bus-open-data
      
      - name: Leave TNDS services data only
        run: |
          mkdir -p services
          cp -r uk-bus-open-data/data/tnds/S/* services/
          rm -rf services/stopPoints
          rm -f services/stops_tnds_only.json
          rm -f services/all_stop_points.json
          rm -rf uk-bus-open-data

          find . -type d | while read dir; do
            count=$(find "$dir" -maxdepth 1 -type f | wc -l)
            size=$(du -sh "$dir" | awk '{print $1}')
            printf "%-50s Files: %-6s Size: %s\n" "$dir" "$count" "$size"
          done

      - name: Delete 
        run: | 
          rm -rf /home/runner/.dotnet
          rm -rf /home/runner/.cargo
          rm -rf /home/runner/.rustup
          rm -rf /home/runner/.nvm
          rm -rf /home/runner/actions-runner/cached/2.329.0/
          rm -rf /home/runner/actions-runner/cached/externals/node20_alpine/
          rm -rf /home/runner/actions-runner/cached/externals/node20/
          rm -rf /home/runner/actions-runner/cached/externals/node24_alpine/
          rm -rf /home/runner/actions-runner/cached/externals/node24/

      - name: Check runner storage space
        run: | 
          find /home/runner/actions-runner/cached/bin -type d | while read dir; do
            count=$(find "$dir" -maxdepth 1 -type f | wc -l)
            size=$(du -sh "$dir" | awk '{print $1}')
            printf "%-50s Files: %-6s Size: %s\n" "$dir" "$count" "$size"
          done
          # find /home/runner/actions-runner/cached/bin -type d | while read dir; do
          #   count=$(find "$dir" -maxdepth 1 -type f | wc -l)
          #   size=$(du -sh "$dir" | awk '{print $1}')
          #   printf "%-50s Files: %-6s Size: %s\n" "$dir" "$count" "$size"
          # done

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: services
          
      # - name: Delete old github-pages artifacts
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     gh api repos/${{ github.repository }}/actions/artifacts \
      #       --jq '.artifacts[] | select(.name=="github-pages") | .id' \
      #       | while read id; do
      #           echo "Deleting artifact id $id"
      #           gh api \
      #             --method DELETE \
      #             repos/${{ github.repository }}/actions/artifacts/$id
      #         done

      # - name: Upload Artifact
      #   id: upload-artifact
      #   uses: actions/upload-artifact@v5
      #   with:
      #     name: 'github-pages'
      #     path: artifact
      #     if-no-files-found: error

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
